// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ecode/v1/ecode.proto

package ecodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error 是業務錯誤碼跨 gRPC 邊界的載體。
//
// pkg/ecode 把它夾進 grpc status 的 details 欄位:
// server 端 ecode → status 時塞入,client 端 status → ecode 時取出,
// 讓 -404 這類業務碼穿過網路後仍是 -404,而不是被壓扁成 codes.Unknown。
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 業務錯誤碼,負數採 HTTP 狀態碼取負的慣例(如 -404 資源不存在)。
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 給人看的錯誤訊息,跨網路保持原樣。
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_ecode_v1_ecode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_ecode_v1_ecode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_ecode_v1_ecode_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ecode_v1_ecode_proto protoreflect.FileDescriptor

const file_ecode_v1_ecode_proto_rawDesc = "" +
	"\n" +
	"\x14ecode/v1/ecode.proto\x12\becode.v1\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageBEZCgithub.com/twtrubiks/grpc-governance-lab/api/proto/ecode/v1;ecodev1b\x06proto3"

var (
	file_ecode_v1_ecode_proto_rawDescOnce sync.Once
	file_ecode_v1_ecode_proto_rawDescData []byte
)

func file_ecode_v1_ecode_proto_rawDescGZIP() []byte {
	file_ecode_v1_ecode_proto_rawDescOnce.Do(func() {
		file_ecode_v1_ecode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ecode_v1_ecode_proto_rawDesc), len(file_ecode_v1_ecode_proto_rawDesc)))
	})
	return file_ecode_v1_ecode_proto_rawDescData
}

var file_ecode_v1_ecode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ecode_v1_ecode_proto_goTypes = []any{
	(*Error)(nil), // 0: ecode.v1.Error
}
var file_ecode_v1_ecode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ecode_v1_ecode_proto_init() }
func file_ecode_v1_ecode_proto_init() {
	if File_ecode_v1_ecode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ecode_v1_ecode_proto_rawDesc), len(file_ecode_v1_ecode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ecode_v1_ecode_proto_goTypes,
		DependencyIndexes: file_ecode_v1_ecode_proto_depIdxs,
		MessageInfos:      file_ecode_v1_ecode_proto_msgTypes,
	}.Build()
	File_ecode_v1_ecode_proto = out.File
	file_ecode_v1_ecode_proto_goTypes = nil
	file_ecode_v1_ecode_proto_depIdxs = nil
}
