// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: relation/v1/relation.proto

package relationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetFollowerCountRequest 是 GetFollowerCount 的請求。
type GetFollowerCountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 使用者 ID。
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowerCountRequest) Reset() {
	*x = GetFollowerCountRequest{}
	mi := &file_relation_v1_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowerCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowerCountRequest) ProtoMessage() {}

func (x *GetFollowerCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_v1_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowerCountRequest.ProtoReflect.Descriptor instead.
func (*GetFollowerCountRequest) Descriptor() ([]byte, []int) {
	return file_relation_v1_relation_proto_rawDescGZIP(), []int{0}
}

func (x *GetFollowerCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// GetFollowerCountResponse 是 GetFollowerCount 的回應。
type GetFollowerCountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 粉絲數。
	Count         int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowerCountResponse) Reset() {
	*x = GetFollowerCountResponse{}
	mi := &file_relation_v1_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowerCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowerCountResponse) ProtoMessage() {}

func (x *GetFollowerCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_v1_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowerCountResponse.ProtoReflect.Descriptor instead.
func (*GetFollowerCountResponse) Descriptor() ([]byte, []int) {
	return file_relation_v1_relation_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowerCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_relation_v1_relation_proto protoreflect.FileDescriptor

const file_relation_v1_relation_proto_rawDesc = "" +
	"\n" +
	"\x1arelation/v1/relation.proto\x12\vrelation.v1\"2\n" +
	"\x17GetFollowerCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"0\n" +
	"\x18GetFollowerCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2r\n" +
	"\x0fRelationService\x12_\n" +
	"\x10GetFollowerCount\x12$.relation.v1.GetFollowerCountRequest\x1a%.relation.v1.GetFollowerCountResponseBKZIgithub.com/twtrubiks/grpc-governance-lab/api/proto/relation/v1;relationv1b\x06proto3"

var (
	file_relation_v1_relation_proto_rawDescOnce sync.Once
	file_relation_v1_relation_proto_rawDescData []byte
)

func file_relation_v1_relation_proto_rawDescGZIP() []byte {
	file_relation_v1_relation_proto_rawDescOnce.Do(func() {
		file_relation_v1_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relation_v1_relation_proto_rawDesc), len(file_relation_v1_relation_proto_rawDesc)))
	})
	return file_relation_v1_relation_proto_rawDescData
}

var file_relation_v1_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_relation_v1_relation_proto_goTypes = []any{
	(*GetFollowerCountRequest)(nil),  // 0: relation.v1.GetFollowerCountRequest
	(*GetFollowerCountResponse)(nil), // 1: relation.v1.GetFollowerCountResponse
}
var file_relation_v1_relation_proto_depIdxs = []int32{
	0, // 0: relation.v1.RelationService.GetFollowerCount:input_type -> relation.v1.GetFollowerCountRequest
	1, // 1: relation.v1.RelationService.GetFollowerCount:output_type -> relation.v1.GetFollowerCountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relation_v1_relation_proto_init() }
func file_relation_v1_relation_proto_init() {
	if File_relation_v1_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relation_v1_relation_proto_rawDesc), len(file_relation_v1_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relation_v1_relation_proto_goTypes,
		DependencyIndexes: file_relation_v1_relation_proto_depIdxs,
		MessageInfos:      file_relation_v1_relation_proto_msgTypes,
	}.Build()
	File_relation_v1_relation_proto = out.File
	file_relation_v1_relation_proto_goTypes = nil
	file_relation_v1_relation_proto_depIdxs = nil
}
